users/applications/home/urls.py
from django.urls import path

from .import views

app_name = 'home_app'

urlpatterns = [
    path('panel/', views.HomeView.as_view(),name='panel'),
]

users/applications/users/urls.py
from django.urls import path

from .import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(),name='user_register'),
    path('login/', views.LoginUser.as_view(),name='user_login'),
    path('logout/', views.LogoutView.as_view(),name='user_logout'),
    path('update/', views.UpdatePasswordView.as_view(),name='update_password'),
    path('verification/<pk>/', views.CodeVerificationView.as_view(),name='user_verification'),
    
]

users/users/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
]

users/applications/home/models.py
from django.db import models

# Create your models here.

users/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('f', 'female'),
    )

    username = models.CharField('Username', max_length=20, unique=True)
    email = models.EmailField()
    first_name = models.CharField('First name', max_length=30, blank=True)
    last_name = models.CharField('First name', max_length=30, blank=True)
    gender = models.CharField('Gender', max_length=1, choices=GENDER_CHOICES, blank=True)
    codregister = models.CharField(max_length=6, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    object = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

users/applications/users/forms.py
from django import forms

from .models import User

from django.contrib.auth import authenticate

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label = 'Password',
        required = True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Password'
            }
        )
    )

    password2 = forms.CharField(
        label = 'Password',
        required = True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Repeat password'
            }
        )

    )
    
    class Meta:

        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'username',
            'last_name',
            'gender',
        )

        def clean_password2(self):
            if self.cleaned_data['password1'] != self.cleaned_date['password2']:
                self.add_error('password2', 'Passwords do not match')


class LoginForm(forms.Form):

    username = forms.CharField(
        label = 'Username',
        required = True,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Username'
            }
        )
    )
    password = forms.CharField(
        label = 'Password',
        required = True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña'
            }
        )

    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('User data is not correct')

        return self.cleaned_data 


class UpdatePasswordForm(forms.Form):

    password = forms.CharField(
        label = 'Password',
        required = True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Current password'
            }
        )

    )

    password2 = forms.CharField(
        label = 'Password',
        required = True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'New password'
            }
        )

    )


class VerificationForm(forms.Form):
    registercode = forms.CharField(required=True)   

    def clean_registercode(self):
        code = self.cleaned_data['registercode']    

        if len(code) == 6:
            active = User.objects.code_validation(
                self.kwargs['pk'],
                code
            )
            if not active:
              raise forms.ValidationError('The code is wrong')   
        else:
            raise forms.ValidationError('The code is wrong')

users/applications/home/views.py
import datetime

from django.views.generic import TemplateView 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
   

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:user_login')

users/applications/users/views.py
from  django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, View
from django.core.mail import send_mail 
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from .forms import UserRegisterForm, LoginForm, UpdatePasswordForm, VerificationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from .functions import code_generator



class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):
        #The code is generated
        code = code_generator()
        user = User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            first_name = form.cleaned_data['first_name'],
            last_name = form.cleaned_data['last_name'],
            gender = form.cleaned_data['gender'],
            codregister = code
        )
        #Send the code to the user's email
        affair = 'Email confirmation'
        message = 'Verification code: ' + code
        sender_mail = 'thisisatest103422@gmail.com'
        send_mail(affair, message, sender_mail,) [form.cleaned_data['email'],]
        #Redirect to validation screen

        return HttpResponseRedirect(
            reverse(
                'users_app:user_verification',
                kwargs={'pk': user.id }
            )
        )


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:panel')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser,self).form_valid(form)

class LogoutView(View):

    def get(self, requests, *args, **kargs):
        logout(requests)
        return HttpResponseRedirect(
            reverse(
                'users_app:user_login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    #view to update user password
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user_login')
    login_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form):
        userrequest = self.request.user
        user = authenticate(
            username=userrequest.username,
            password=form.cleaned_data['password']
        )
        if user:
            new_password = form.cleaned_data['password2']
            userrequest.set_password(new_password)
            userrequest.save()

        logout(self.request)    
        return super(UpdatePasswordView,self).form_valid(form)


class CodeVerificationView(FormView):
    template_name = 'users/verification.html'
    form_class = VerificationForm
    success_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form): 
        
        return super(CodeVerificationView, self).form_valid(form)

users/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>User panel</h1>
    <h2>Wellcome: {{user}}</h2>
    <ul>
        <li><a href="{% url 'users_app:user_logout' %}">Sign off</a></li>
        <li><a href="#">Update data</a></li>
    </ul>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>System login</h1>
    <form method="POST">{% csrf_token %}
            {{form.as_p}}
            <button type="submit">Login</button>
    </form>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Registar nuevo usuario</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
   
</body>
</html>

users/templates/users/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Change Password: {{ user.username }}</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upgrade</button>
    </form>
</body>
</html>

users/templates/users/verification.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verification</title>
</head>
<body>
    <h1>Verification email</h1>
    <h2>Enter the verification code</h2>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Confirm</button>
    </form>
</body>
</html>